# GoReleaser configuration for Rust project
# Documentation at https://goreleaser.com
version: 2

before:
  hooks:
    - rustup default stable
    - cargo install cargo-zigbuild
    - cargo fetch

# Actually builds the binaries.
builds:
  - builder: rust
    binary: meda
    env:
      - CARGO_TERM_COLOR=always
    flags:
      - --release
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu

# Creates archives for each target.
archives:
  - formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - ch-vm.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: "aktech"
    name: "chvisor-example"
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
