name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install qemu-utils genisoimage iptables jq -y
        sudo apt-get install sshpass
    - name: Give the runner user rw access to /dev/kvm
      run: sudo setfacl -m u:${USER}:rw /dev/kvm
    - name: Run Test
      run: cargo test

