name: All Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # This workflow now acts as a meta-workflow that depends on all other test workflows
  all-tests:
    name: All Tests Complete
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - integration-basic
      - integration-vm-creation
      - integration-vm-operations
      - integration-advanced
    steps:
      - name: All tests passed
        run: echo "✅ All test workflows completed successfully!"

  # Unit tests and linting workflow
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  # Basic integration tests (fast, no VM operations)
  integration-basic:
    uses: ./.github/workflows/integration-tests-basic.yml

  # VM creation tests
  integration-vm-creation:
    uses: ./.github/workflows/integration-tests-vm-creation.yml

  # VM operations tests
  integration-vm-operations:
    uses: ./.github/workflows/integration-tests-vm-operations.yml

  # Advanced integration tests (slow, complex operations)
  integration-advanced:
    uses: ./.github/workflows/integration-tests-advanced.yml


